### ISSUE TITLE
Issue when user navigates away

### ISSUE THREAD

**Issue by RCatersels** [appronto/DataviewLoader#3]
When I open a page where this widget is used and the user navigates away the microflow and popup is not stopped. After the microflow finishes and the data is retrieved the user will suddenly see only this popup even if the user is no longer on the page.

Regards,

Ronald

**Comment by joelvdgraaf** [comment]
Hi Ronald, Thanks for reporting! I've aso found the bug and fixed it already. It's just in the last testing phase. I will release this fix to the appstore shortly.

**Comment by joelvdgraaf** [comment]
The new version of the widget is in approval in the appstore based on the version 1.1 of github

**Comment by RCatersels** [comment]
Kudo's for the sollution speed!

**Comment by RCatersels** [comment]
The new widget does not work anymore. The datasource microflow never seems to be triggered. I put a breakpoint on it but the break is never triggered.
