### ISSUE TITLE
The datasource microflow is never triggered anymore

### ISSUE THREAD

**Issue by RCatersels** [appronto/DataviewLoader#4]
After the update I first thought that the widget was working because moving away was working and I did not get to see the popup page. Problem is that the spinner never stops loading. A breakpoint on the datasource microflow was never triggered so it looks like there is a problem with triggering the microflow.

Regards,
Ronald

**Comment by RCatersels** [comment]
And the widget is in a snippet. Will see if removing the snippet has some influance.

**Comment by RCatersels** [comment]
Found the culprit. It's the combination of the ShowByCondition widget and your widget. When I remove the showbycondition widget the datasource does gets triggered. Problem is that we customize visibility of blocks. We have settings where we define if a block is visible or not. Your first version did not clash with the showbycondition widget as long as it was placed in a snippet. Otherwise is would always show even when the showbycondition was set to false.

**Comment by joelvdgraaf** [comment]
Issue solved I assume
