### ISSUE TITLE
Tab pages don't load when visibility handling is set to True

### ISSUE THREAD

**Issue by LaDuelo** [appronto/DataviewLoader#6]
I have a page in my project that displays a lot of information, so I categorized it using a tab container. When I put a tab's content into a data view loader as described in the documentation and set the Visiblity Handling flag to True, the contents never load and all I see is a never ending spinning circle. No errors are thrown in the browser console or Mendix console. I'm using Mendix 8 BETA 1 and Google Chrome.
Setting Visibility Handling to False does load all contents within each tab, but that defeats the purpose of lazy loading each tab.
Any suggestions? Is this a known issue?

**Comment by joelvdgraaf** [comment]
This is a known issue with Mendix 8 and the widget isn't compatible with Mendix 8, due the changes in the Mendix Client API. After the first real release of 8 we will upgrade the compatibility. In beta 3 for example the DOM and API will change, so fixing the widget now is a waste of time.

**Comment by LaDuelo** [comment]
I thought this might be the case. Looking forward to this widget being updated for the real release of Mx8. Thank you for the quick reply!
